FROM php:8.1-apache

# Copia tu código al directorio raíz del servidor web
COPY . /var/www/html/

# Da permisos si hace falta
RUN chown -R www-data:www-data /var/www/html

# Exponer el puerto 80
EXPOSE 80
# 